---

- name: Install python packages for webapp
  pip:
    name:
      - arrow==0.15.*
      - Cerberus==1.3.*
      - cryptography==2.8
      - SQLAlchemy==1.3.*
      - eventlet==0.25.*
      - gunicorn==20.0.*
      - Flask==1.1.*
      - Flask-SocketIO==4.2.*
      - Flask-Cors==3.0.*
      - Flask-SQLAlchemy==2.4.*
      - Flask-JWT-Extended==3.24.*
    virtualenv: '{{ remote_user_dir_path }}/.pyenv/versions/{{ webapp_virtualenv_name }}'
    state: present
  become: no
