export const GET_AUTH_DATA = 'GET_AUTH_DATA';
export const SAVE_AUTH_DATA = 'SAVE_AUTH_DATA';
export const FETCH_AUTH_DATA_REJECTED = 'FETCH_AUTH_DATA_REJECTED';

export const FETCH_CLIENT_LIST = 'FETCH_CLIENT_LIST';
export const FETCH_CLIENT_LIST_REJECTED = 'FETCH_CLIENT_LIST_REJECTED';
export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST';
